# Generated by Django 4.2.17 on 2025-01-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['animal_name']},
        ),
    ]
